### PR TITLE
Addressing DACS and EAC-CPF Conflict Over Approximate Dates

### PR DESCRIPTION
**Pull request by michelsd**
Change request submitted by Dan Michelson based on issue #19.

### Chapters to change
11.1 Dates of Existence

### Proposed change
- Update instructions in 11.1.1 for recording approximate dates in archival authority records to accommodate use of '@notBefore' and '@notAfter'.
- Add example of using this language.
- Further improve flexibility and resolve inconsistency between rules and examples by changing "year" to "date" in  11.1.1. 

### Justification for proposed change
- Instructions for recording approximate dates are incompatible with EAC-CPF. 
- DACS 11.1.1 is far more prescriptive than DACS 2.4.  Given the removal of Part III, this prescriptiveness now seems out of place.
- Precluding the use of `@notBefore` and `@notAfter` prevents recording potentially valuable date information.  EAD3 now also contains equivalent tags, but these are not forbidden by the more flexible rules in DACS 2.4.
- The use of the word "year," rather than "date," in the 11.1.1 instructions conflicts with the examples given in the same section.

### Impact of proposed change
This change removes a barrier to creating archival authority records using DACS and EAC-CPF.  It also allows more precise dating.  No existing description would fall out of compliance due to this change.

### CODE REVIEW

**Comment by milesnimer** [comment]
The guidelines in 11.1.1 were originally based on RDA date entry conventions, some of which have been superseded at this point, with the examples focused on human-readable values rather than normalized dates. If there is interest in maintaining compatibility with RDA, some adjustments may be needed in DACS for their updated rules (see [https://access.rdatoolkit.org/Content/Index?externalId=en-US_ala-70924ad2-277f-3cd6-b2ad-332d0945e346]). The current version of DACS also generally does not include coding examples. Is there still work being done to develop a compendium of encoding examples for each element, or is TS-DACS intending to integrate them back into the text? In the case of @notBefore, using the term "approximately" as a textual prefix would not necessarily preclude its use in record encoding. For example: 

`<existDates>
                <dateRange>
                    <fromDate localType="http://socialarchive.iath.virginia.edu/control/term#Birth"
                        notBefore="1801">approximately 1801</fromDate>
                    <toDate localType="http://socialarchive.iath.virginia.edu/control/term#Death"
                        standardDate="1877-08-29">1877 August 29</toDate>
                </dateRange>
            </existDates>`

**Comment by michelsd** [comment]
@milesnimer I don't have a subscription to RDA, so I cannot access the link you included.

TS-DACS has not been working on adding encoding examples to existing rules during my time on the subcommittee (2017-present).

I see your point that it is reasonable to interpret 11.1 as only requiring approximately as a textual prefix, but I don't know why we would want to require it in your example.  What benefit does it serve?

The broader issue that you're bringing up is the lack of distinction throughout DACS between how data should be encoded and how it should be displayed.  For example, the year/month/day format is essential for encoding, but is unfamiliar to most end users of archival description.

**Comment by milesnimer** [comment]
As an optional or alternative guideline, I have no objection to this proposed addition as long as it does not preclude the use of the term "approximately" for approximate dates.

**Comment by gwiedeman** [comment]
Addresses #19

**Comment by katyrawdon** [comment]
> As an optional or alternative guideline, I have no objection to this proposed addition as long as it does not preclude the use of the term "approximately" for approximate dates.

@milesnimer I'm following up on comments on proposed changes here, and wanted to make sure you feel that your concern has been addressed? 

The suggested alteration to [11.1.1](https://saa-ts-dacs.github.io/dacs/08_part_II/04_chapter_11/01_dates_of_existence.html) is to replace the language "If the year can only be approximated, record the date in the form _approximately_ [year]" with "If the date can only be approximated, record the date in the form _approximately_ [date]. Alternatively, record earliest possible or latest possible dates" - and add an example to 11.1.2 with "not before [date]" and/or "not after [date]" language. The option to use "approximately" would still remain. @michelsd can correct me if I'm wrong about this!

**Pull request merged**
