### PR TITLE
Create License Archival Description Section

### PR DESCRIPTION
**Pull request by p-galligan**
DACS Change Request
Submitted by Alston Cobourn, Patrick Galligan

Brief description of the component of DACS to be changed as well as the proposed change.
We are writing to request the creation of a new required DACS element 8.1 called "License for Archival Description" in Chapter 8 that would proceed the existing value added “Description Control” element. Repositories would use this element to declare that they are making the finding aid itself available under a license, such as machine actionable Creative Commons licenses.  We propose the following text:

2. Justification for the proposed change. 
  As Merrilee Proffitt from OCLC discussed in a Society of American Archivist (SAA) panel at the 2016 conference, opening finding aids for reuse is beneficial to researchers, particularly those in the digital humanities, as it allows them to use the data about our collections in new and interesting ways, such as text mining.  As researchers develop new ways to interact with our collections and finding aids, cultural heritage institutions need standardized ways to tell researchers and future archivists the ways in which they can use finding aid data.  Placing licenses on our finding aids affords us another way to fulfill our mission to help researchers use the archival collections with which we are entrusted.  Additionally, promoting open licensing aligns with our professional value to promote open and transparent cultural heritage.
The SAA Technical Subcommittee on Encoded Archival Standards has added a <rightsdeclaration> element to its EAD3 1.1 release in hopes of accommodating this need.  This release is now out for community review.  I have submitted a new feature request to ArchivesSpace asking for the creation of a corresponding field in the Finding Aid Information section of Resource records.  Bringing both standards and this system that utilizes them into alignment on this point would both provide a guideline for how to implement licenses as well as the ability to do so in a standardized way.

3.  Impact of the proposed change.
Adding this DACS element would encourage archives to open their finding aids by enabling them to do so easily.  Since archives very clearly own the copyrights to their finding aids and generating Creative Commons licenses is simple, the lack of appropriate DACS and EAD3 elements in which to record the license information are the only real impediments to archives that wish to open their finding aids.  Clarifying the restrictions on how the data about our collections can be used also has the potential to increase the awareness of our collections and make archives relevant to new researchers and research methods.

### CODE REVIEW

**Comment by rockivist** [comment]
I heartily second this change request.

The only objection from the community that I would anticipate is whether or not it should be required. I'm in favor of this being a required element, but I think the statement underestimates the impact of the proposed change. Adding a CC (or other) license to existing description wouldn't be onerous. For some institutions, negotiating a clear policy with their legal counsel could be. It's important, even essential, to do, but as this is discussed in the community we shouldn't underestimate or downplay the potential political hurdles to full implementation.

That concern aside, let's do it.

**Comment by anarchivist** [comment]
I'd like to offer a suggestion that we potentially expand this proposal to consider not just licenses, but also rights statements for the description itself. It is a subtle but important distinction. A few cases come to mind:

* Institutions still want claim copyright explicitly without issuing description under a specific license. 
* Outside the US, data publishers may have both copyright and database rights on datasets they publish, and may need to assign more than one license or rights statement as part of that. (See [here](https://meta.wikimedia.org/wiki/Wikilegal/Database_Rights) for potentially useful info.)

**Comment by p-galligan** [comment]
Updated change request to attempt to make room for @anarchivist 's comments about rights statements outside of licenses. 

Updated DACS Change Request
Submitted by Alston Cobourn, Patrick Galligan

Brief description of the component of DACS to be changed as well as the proposed change.
We are writing to request the creation of a new required DACS element 8.1 called "Rights Statement for Archival Description" in Chapter 8 that would proceed the existing value added “Description Control” element. Repositories would use this element to declare that they are making the archival description itself available for reuse. Repositories could use a machine actionable Creative Commons license to articulate the terms of use, but they are not limited to this.

2. Justification for the proposed change. 
  As Merrilee Proffitt from OCLC discussed in a Society of American Archivist (SAA) panel at the 2016 conference, opening archival descriptions for reuse is beneficial to researchers, particularly those in the digital humanities, as it allows them to use the data about our collections in new and interesting ways, such as text mining.  As researchers develop new ways to interact with our collections and archival descriptions, cultural heritage institutions need standardized ways to tell researchers and future archivists the ways in which they can use archival description data.  Stating these rights directly in the archival descriptions themselves affords us another way to fulfill our mission to help researchers use the archival collections with which we are entrusted.  Additionally, allowing our archival descriptions to be reused aligns with our professional value to promote open and transparent cultural heritage.
The SAA Technical Subcommittee on Encoded Archival Standards has added a <rightsdeclaration> element to its EAD3 1.1 release in hopes of accommodating this need.  This release is now out for community review.  I have submitted a new feature request to ArchivesSpace asking for the creation of a corresponding field in the Finding Aid Information section of Resource records.  Bringing both standards and this system that utilizes them into alignment on this point would both provide a guideline for how to implement rights  as well as the ability to do so in a standardized way.

3.  Impact of the proposed change.
Adding this DACS element would encourage archives to open their archival descriptions by enabling them to do so easily.  Since archives very clearly own the copyrights to description created by the archival repository, the lack of appropriate DACS and EAD3 elements in which to record the rights information is the only real impediment to archives that wish to open their archival descriptions.  Clarifying the restrictions on how the data about our collections can be used also has the potential to increase the awareness of our collections and make archives relevant to new researchers and research methods.

**Comment by KateBowersHarvard** [comment]
I agree with the requirement, but I would like to see a small amendment to the language. Because DACS is applied not just to archival inventories and EAD, but to single-level descriptions that may be encoded in MARC in library systems or in other systems where there are system-level sharing licenses or institutional-level terms of use are recorded, making this required at the single-level minimum could be problematic and lead to conflicts when system-level terms change. Some language suggesting that **system-level** licenses or terms of use statements satisfy this requirement, rather than requiring this element to be present as text in every description, would be beneficial.  For an example of a system-level term of use a statement see: https://library.harvard.edu/open-metadata#Bibliographic-Dataset-Use-Terms

**Comment by seth-shaw-unlv** [comment]
[Appendix C Crosswalks](https://github.com/saa-ts-dacs/dacs/blob/master/appendices/appendix_c_crosswalks.md#appendix-c-crosswalks) should also be updated to reflect the numbering change for Description Control (8.1->8.2).

**Comment by helrond** [comment]
Strongly in support of this change - it's high time we started taking reuse of our intellectual labor seriously!

Regarding @KateBowersHarvard's comment - I'm not sure the rule as written precludes that interpretation, and more generally, I'm not sure DACS cares whether a human or a machine supplies the content of a particular descriptive element.

Two very small administrative changes:

1. Examples should be wrapped in a `<p class="dacs-example">` tag (see other examples throughout the text).
2. [Single-level minimum requirements](https://github.com/saa-ts-dacs/dacs/blob/master/part_I/chapter_1.md#requirements-for-single-level-descriptions) need to be updated as well.

**Comment by KateBowersHarvard** [comment]
@helrond -- agree, and I had thought of that. However, strongly hope that at either a note or at least one example includes the our-entire-MARC-data-has-this-license scenario.

**Comment by rovinghistorian** [comment]
I second @rockivist 's mention of making this a required element.  At least in the beginning, I think this would be better as an optional element in order to help institutions transition and grapple with some of the issues at their institutional level; making it required could be revisited a couple/few years down the line in a review.

**Comment by John-Rees** [comment]
This will be a great benefit not only to data reuse but also to authorship attribution as expressed by @helrond.

This topic has come up during many of the aggregator brownbags at SAA, It will help disambiguate rights to the archival description content vs that of any discovery software or institutional branding wrappers. My concern about @KateBowersHarvard use case, if I understand it correctly, is rights statements should be explicitly recorded within each individual description itself and not inferred from external sources such as a FAQ or Help page. Machine processing of our descriptions such as that performed by aggregators or linked data use cases would continue to be a challenge with inferred data.

I also second @rovinghistorian comment about making the element optional, but mandatory if available.

**Comment by KateBowersHarvard** [comment]
My concern stands that it will be impossible to manage rights statements at scale or at an institutional level if they are also added as text to some individual descriptions (i.e. keyed into 500 notes in MARC).  

RE: 
<blockquote>`My concern about @KateBowersHarvard use case, if I understand it correctly, is rights statements should be explicitly recorded within each individual description itself and not inferred from external sources such as a FAQ or Help page. `</blockquote>

An individual archivist working in a parent institution is creating work for hire (disclaimer: I'm not a lawyer). The license or terms of use for the records they create while being paid by that institution cannot differ from the those that parent institution grants (disclaimer: I'm still not a lawyer), unless the institution facilitates this. At scale, attempting to manage two statements will probably result in conflicts in which the keyed-in statement makes rights legally indefensible (disclaimer: I continue to not be a lawyer), misleading, or at least confusing. 

The best answer, I suspect, would be to include the applicable rights statement (or better, a URI to the rights statement) upon export of the discovery metadata from such a system. Should the terms and conditions change, there will inevitably be conflicting statements. 

At scale, this is a display, public UI, and metadata sharing exercise.

**Comment by phirtle1** [comment]
This is a much needed change.  May I suggest, however, that the example of use be slightly changed to include the qualification that "Except where otherwise noted, this work is available under [license version]."  This would be a subtle reminder to authors of finding aids that if they are including material from outside sources (photographs, biographical descriptions, etc.), they need to separately mark that content.

**Comment by gwiedeman** [comment]
I strongly support this proposal. Adding permissive rights statements will facilitate access not just to archival description, but also enable further access to archival materials though new uses of archival description.

By requiring statements within DACS, archivists are also ensuring that this information will be maintained along with the description itself, and persist long into the future.

While I think some repositories may not be able to implement this change immediately, requiring it should not be difficult in our case. If the element is not required initially, I would support an explicit review timeline where that decision would be revisited.

**Comment by save4use** [comment]
I agree with the proposal, including @anarchivist 's and @KateBowersHarvard's suggestions. 

However, I am not in favor of making it a required field, as @rockivist suggested. There are many reasons a repository may not be able to provide a statement, including having a significant barrier to getting internal institutional buy-in (some places I've worked would have required this to go through central legal counsel or licensing, a process which could take months or years, would have required significant resources that could have been used elsewhere, and may not have resulted in the outcome we wanted). Since this is not something that many places can just choose to immediately implement, I don't think it should be required.

**Comment by ngerth** [comment]
I also write in support of the proposal. As many others point out, this move will help foster innovative use of descriptive metadata and, as a result, more access to materials.

In terms of making the field required, I think that laying out an explicit timeline for adoption or revisiting the decision, as suggested by @gwiedeman, makes a great deal of sense. For some institutions, the legal considerations will take some time, especially if counsel is bogged down with other matters, see the post by @save4use above. A timeline will help keep this important change from falling off the radar, while also giving institutions time to foster buy-in.

**Comment by jallibunn** [comment]
As one of the individuals who worked with Merrilee on this project (and with CC licenses for finding aids on Archives West http://archiveswest.orbiscascade.org/  live as of tomorrow!), I heartily support this change. In most cases, the application of a CC0 or CC-BY is a simple decision; the fact that there are barriers of institutional buy-in or bureaucracy should not be a barrier to moving forward with this change and encouraging adoption. I appreciate the work of all of those involved and look forward to having this fully reconciled in DACS, ASpace, and EAD3.

**Comment by hannahfrost** [comment]
As a member of the Collections as Data project team, I strongly support this proposal. Last week the project team hosted the National Forum 2 at UNLV with a diverse set of practitioners, including archivists, metadata librarians, and humanities faculty. A clear outcome of one of the exercises we conducted is that explicit license statements (along with right statements) are deemed critically necessary to advance the possibilities and opportunities afforded by computational access to collections and the metadata about them. The consensus of those present was that this is low hanging fruit and has high value as a means of increasing exposure to archival collections by discovery systems broadly speaking.

**Pull request merged**
