### PR TITLE
Adding scripts and slides for DACS video series

### PR DESCRIPTION
**Pull request by amhanson9**
These scripts and PowerPoint slides (when available) are the object of record for the free DACS video series produced by TS-DACS and collaborators. When updates to the videos are made, they should use these documents as a starting point.

### CODE REVIEW

**Comment by meau** [comment]
Thanks for this work, Adriane! I wonder if this should be in a separate repository belonging to saa-ts-dacs called workshop, so that the dacs repository is just about the standard. What do you think?

**Comment by amhanson9** [comment]
I can go either way on this being its own repository, although I'm leaning towards keeping it all together. Practically speaking, this material is so closely related it might be easier to use all in one place, rather than navigating back and forth. We also have a user community that may have a lot of people that are new to GitHub, and any added complexity, even if it is just going back and forth between repositories, could add to the intimidation factor, Philosophically, I feel like the content is close enough to all work together - we have the standard itself and in the video materials we have information about the standard.

That said, I can also see it working as its own repository, if that makes more sense to most people. Are there GitHub-related advantages to managing related things as different repositories?

**Comment by meau** [comment]
The repository is where we're telling the community to find the most up-to-date version of the standard. Since this isn't the standard, and since it didn't have to go through the same paces as the standard (community approval, council approval), I'd prefer to have it in it's own repository.

**Comment by amhanson9** [comment]
That makes sense - we will make this its own repository. Would everyone be comfortable with it being a repository for resources about DACS generally or would we rather have it specifically be about the workshop?

**Comment by meau** [comment]
Created workshop repo for this to go into, closing pull request.

**Pull request closed without merging**
